title: Ember Rising
description: "Rebellion in a Broken System — a visual novel and cyberpunk universe."

remote_theme: volny/creative-theme-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme   # 👈 required so GitHub loads the Volny Creative theme
url: "https://thishas.github.io"
baseurl: "/emberrising-site"

# Navigation links (use anchors to avoid path errors)
nav:
  - name: Home
    link: "#page-top"
  - name: The World
    link: "#about"
  - name: Stories
    link: "#services"
  - name: Play Demo
    link: "#portfolio"
  - name: Join
    link: "#contact"

# Contact information
email: ignite.emberrising@gmail.com
